# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'SDKDemoOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for SDKDemoOC
#pod 'SVProgressHUD'

pod 'Toast'

end
